# Python Pandas Part_4
# Querying Your Dataset

In [1]:
import requests

download_url = "https://raw.githubusercontent.com/fivethirtyeight/data/master/nba-elo/nbaallelo.csv"
target_csv_path = "nba_all_elo.csv"

response = requests.get(download_url)
response.raise_for_status()    # Check that the request was successful
with open(target_csv_path, "wb") as f:
    f.write(response.content)
print("Download ready.")

Download ready.

In [3]:
import pandas as pd
nba = pd.read_csv("nba_all_elo.csv")
nba.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN

 select rows based on the values in your dataset’s columns to query your data.

# create a new DataFrame that contains only games played after 2010

In [6]:
pd.set_option("display.max.columns", None)
nba.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,66,1300.0000,1293.2767,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,68,1300.0000,1306.7233,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,63,1300.0000,1309.6521,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,47,1306.7233,1297.0712,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,33,1300.0000,1279.6189,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN

In [7]:
games_after_2010 = nba[nba['year_id'] > 2010]

In [8]:
games_after_2010

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
113656,56829,201010260BOS,NBA,1,2011,10/26/2010,1,0,MIA,Heat,80,1547.3638,1543.1600,45.141479,BOS,Celtics,88,1625.0994,1629.3031,A,L,0.264418,NaN
113657,56829,201010260BOS,NBA,0,2011,10/26/2010,1,0,BOS,Celtics,88,1625.0994,1629.3031,53.754559,MIA,Heat,80,1547.3638,1543.1600,H,W,0.735582,NaN
113658,56830,201010260LAL,NBA,1,2011,10/26/2010,1,0,HOU,Rockets,110,1504.1956,1502.5969,40.900764,LAL,Lakers,112,1647.6016,1649.2002,A,L,0.197632,NaN
113659,56830,201010260LAL,NBA,0,2011,10/26/2010,1,0,LAL,Lakers,112,1647.6016,1649.2002,55.608730,HOU,Rockets,110,1504.1956,1502.5969,H,W,0.802368,NaN
113660,56831,201010260POR,NBA,1,2011,10/26/2010,1,0,PHO,Suns,92,1643.0225,1630.6204,53.879230,POR,Trailblazers,106,1552.8141,1565.2162,A,L,0.485912,NaN
113661,56831,201010260POR,NBA,0,2011,10/26/2010,1,0,POR,Trailblazers,106,1552.8141,1565.2162,47.416088,PHO,Suns,92,1643.0225,1630.6204,H,W,0.514088,NaN
113662,56832,201010270CLE,NBA,0,2011,10/27/2010,1,0,CLE,Cavaliers,95,1610.9791,1617.5342,52.629322,BOS,Celtics,87,1629.3031,1622.7480,H,W,0.615423,NaN
113663,56832,201010270CLE,NBA,1,2011,10/27/2010,2,0,BOS,Celtics,87,1629.3031,1622.7480,53.130306,CLE,Cavaliers,95,1610.9791,1617.5342,A,L,0.384577,NaN
113664,56833,201010270DAL,NBA,1,2011,10/27/2010,1,0,CHA,Hornets,86,1524.3628,1517.1617,42.427971,DAL,Mavericks,101,1572.3136,1579.5146,A,L,0.299082,NaN
113665,56833,201010270DAL,NBA,0,2011,10/27/2010,1,0,DAL,Mavericks,101,1572.3136,1579.5146,48.870228,CHA,Hornets,86,1524.3628,1517.1617,H,W,0.700918,NaN
113666,56834,201010270DEN,NBA,0,2011,10/27/2010,1,0,DEN,Nuggets,110,1573.8165,1585.5883,49.481976,UTA,Jazz,88,1575.7539,1563.9822,H,W,0.637492,NaN
113667,56834,201010270DEN,NBA,1,2011,10/27/2010,1,0,UTA,Jazz,88,1575.7539,1563.9822,47.289753,DEN,Nuggets,110,1573.8165,1585.5883,A,L,0.362508,NaN
113668,56835,201010270GSW,NBA,0,2011,10/27/2010,1,0,GSW,Warriors,132,1432.7798,1438.4199,34.231400,HOU,Rockets,128,1502.5969,1496.9568,H,W,0.543328,NaN
113669,56835,201010270GSW,NBA,1,2011,10/27/2010,2,0,HOU,Rockets,128,1502.5969,1496.9568,40.309204,GSW,Warriors,132,1432.7798,1438.4199,A,L,0.456672,NaN
113670,56836,201010270LAC,NBA,0,2011,10/27/2010,1,0,LAC,Clippers,88,1366.6393,1359.6786,26.555721,POR,Trailblazers,98,1565.2162,1572.1769,H,L,0.361824,NaN
113671,56836,201010270LAC,NBA,1,2011,10/27/2010,2,0,POR,Trailblazers,98,1565.2162,1572.1769,48.126297,LAC,Clippers,88,1366.6393,1359.6786,A,W,0.638176,NaN
113672,56837,201010270MEM,NBA,1,2011,10/27/2010,1,0,ATL,Hawks,119,1564.2256,1577.6614,48.682823,MEM,Grizzlies,104,1463.6671,1450.2313,A,W,0.500804,NaN
113673,56837,201010270MEM,NBA,0,2011,10/27/2010,1,0,MEM,Grizzlies,104,1463.6671,1450.2313,35.442268,ATL,Hawks,119,1564.2256,1577.6614,H,L,0.499196,NaN
113674,56838,201010270MIN,NBA,0,2011,10/27/2010,1,0,MIN,Timberwolves,116,1307.7046,1302.8744,21.623932,SAC,Kings,117,1356.5649,1361.3951,H,L,0.573069,NaN
113675,56838,201010270MIN,NBA,1,2011,10/27/2010,1,0,SAC,Kings,117,1356.5649,1361.3951,26.713676,MIN,Timberwolves,116,1307.7046,1302.8744,A,W,0.426931,NaN
113676,56839,201010270NJN,NBA,1,2011,10/27/2010,1,0,DET,Pistons,98,1391.2914,1386.8892,29.114353,NJN,Nets,101,1352.3951,1356.7974,A,L,0.412960,NaN
113677,56839,201010270NJN,NBA,0,2011,10/27/2010,1,0,NJN,Nets,101,1352.3951,1356.7974,26.291695,DET,Pistons,98,1391.2914,1386.8892,H,W,0.587040,NaN
113678,56840,201010270NOH,NBA,0,2011,10/27/2010,1,0,NOH,Pelicans,95,1447.1117,1453.2205,35.750366,MIL,Bucks,91,1537.7723,1531.6636,H,W,0.513437,NaN
113679,56840,201010270NOH,NBA,1,2011,10/27/2010,1,0,MIL,Bucks,91,1537.7723,1531.6636,43.944649,NOH,Pelicans,95,1447.1117,1453.2205,A,L,0.486563,NaN
113680,56841,201010270OKC,NBA,1,2011,10/27/2010,1,0,CHI,Bulls,95,1491.0172,1486.0060,39.161682,OKC,Thunder,106,1572.2351,1577.2463,A,L,0.260538,NaN
113681,56841,201010270OKC,NBA,0,2011,10/27/2010,1,0,OKC,Thunder,106,1572.2351,1577.2463,48.640808,CHI,Bulls,95,1491.0172,1486.0060,H,W,0.739462,NaN
113682,56842,201010270PHI,NBA,0,2011,10/27/2010,1,0,PHI,Sixers,87,1413.7129,1404.4315,30.820885,MIA,Heat,97,1543.1600,1552.4414,H,L,0.457723,NaN
113683,56842,201010270PHI,NBA,1,2011,10/27/2010,2,0,MIA,Heat,97,1543.1600,1552.4414,46.102634,PHI,Sixers,87,1413.7129,1404.4315,A,W,0.542277,NaN
113684,56843,201010270SAS,NBA,0,2011,10/27/2010,1,0,SAS,Spurs,122,1594.2832,1599.3099,50.849224,IND,Pacers,109,1492.3812,1487.3545,H,W,0.761740,NaN
113685,56843,201010270SAS,NBA,1,2011,10/27/2010,1,0,IND,Pacers,109,1492.3812,1487.3545,39.302872,SAS,Spurs,122,1594.2832,1599.3099,A,L,0.238260,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126284,63143,201505190GSW,NBA,0,2015,5/19/2015,93,1,GSW,Warriors,110,1787.3469,1789.7388,66.537224,HOU,Rockets,106,1669.5398,1667.1479,H,W,0.777957,NaN
126285,63143,201505190GSW,NBA,1,2015,5/19/2015,95,1,HOU,Rockets,106,1669.5398,1667.1479,57.136570,GSW,Warriors,110,1787.3469,1789.7388,A,L,0.222043,NaN
126286,63144,201505200ATL,NBA,0,2015,5/20/2015,95,1,ATL,Hawks,89,1613.9390,1603.6616,51.180210,CLE,Cavaliers,97,1678.9756,1689.2529,H,L,0.550147,NaN
126287,63144,201505200ATL,NBA,1,2015,5/20/2015,93,1,CLE,Cavaliers,97,1678.9756,1689.2529,59.051449,ATL,Hawks,89,1613.9390,1603.6616,A,W,0.449853,NaN
126288,63145,201505210GSW,NBA,0,2015,5/21/2015,94,1,GSW,Warriors,99,1789.7388,1791.2300,66.632729,HOU,Rockets,98,1667.1479,1665.6567,H,W,0.782677,NaN
126289,63145,201505210GSW,NBA,1,2015,5/21/2015,96,1,HOU,Rockets,98,1667.1479,1665.6567,57.004177,GSW,Warriors,99,1789.7388,1791.2300,A,L,0.217323,NaN
126290,63146,201505220ATL,NBA,0,2015,5/22/2015,96,1,ATL,Hawks,82,1603.6616,1591.4017,49.964417,CLE,Cavaliers,94,1689.2529,1701.5128,H,L,0.520724,NaN
126291,63146,201505220ATL,NBA,1,2015,5/22/2015,94,1,CLE,Cavaliers,94,1689.2529,1701.5128,60.073715,ATL,Hawks,82,1603.6616,1591.4017,A,W,0.479276,NaN
126292,63147,201505230HOU,NBA,1,2015,5/23/2015,95,1,GSW,Warriors,115,1791.2300,1813.4543,68.002609,HOU,Rockets,80,1665.6567,1643.4324,A,W,0.536737,NaN
126293,63147,201505230HOU,NBA,0,2015,5/23/2015,97,1,HOU,Rockets,80,1665.6567,1643.4324,54.985523,GSW,Warriors,115,1791.2300,1813.4543,H,L,0.463263,NaN
126294,63148,201505240CLE,NBA,0,2015,5/24/2015,95,1,CLE,Cavaliers,114,1701.5128,1703.7124,60.254032,ATL,Hawks,111,1591.4017,1589.2021,H,W,0.770210,NaN
126295,63148,201505240CLE,NBA,1,2015,5/24/2015,97,1,ATL,Hawks,111,1591.4017,1589.2021,49.744450,CLE,Cavaliers,114,1701.5128,1703.7124,A,L,0.229790,NaN
126296,63149,201505250HOU,NBA,1,2015,5/25/2015,96,1,GSW,Warriors,115,1813.4543,1797.8933,67.053963,HOU,Rockets,128,1643.4324,1658.9934,A,L,0.599427,NaN
126297,63149,201505250HOU,NBA,0,2015,5/25/2015,98,1,HOU,Rockets,128,1643.4324,1658.9934,56.407814,GSW,Warriors,115,1813.4543,1797.8933,H,W,0.400573,NaN
126298,63150,201505260CLE,NBA,0,2015,5/26/2015,96,1,CLE,Cavaliers,118,1703.7124,1712.1232,60.934734,ATL,Hawks,88,1589.2021,1580.7914,H,W,0.774661,NaN
126299,63150,201505260CLE,NBA,1,2015,5/26/2015,98,1,ATL,Hawks,88,1589.2021,1580.7914,48.898579,CLE,Cavaliers,118,1703.7124,1712.1232,A,L,0.225339,NaN
126300,63151,201505270GSW,NBA,1,2015,5/27/2015,99,1,HOU,Rockets,90,1658.9934,1654.6359,56.013645,GSW,Warriors,104,1797.8933,1802.2509,A,L,0.201778,NaN
126301,63151,201505270GSW,NBA,0,2015,5/27/2015,97,1,GSW,Warriors,104,1797.8933,1802.2509,67.324539,HOU,Rockets,90,1658.9934,1654.6359,H,W,0.798222,NaN
126302,63152,201506040GSW,NBA,1,2015,6/4/2015,97,1,CLE,Cavaliers,100,1712.1232,1708.1705,60.616585,GSW,Warriors,108,1802.2509,1806.2035,A,L,0.250779,NaN
126303,63152,201506040GSW,NBA,0,2015,6/4/2015,98,1,GSW,Warriors,108,1802.2509,1806.2035,67.566650,CLE,Cavaliers,100,1712.1232,1708.1705,H,W,0.749221,NaN
126304,63153,201506070GSW,NBA,1,2015,6/7/2015,98,1,CLE,Cavaliers,95,1708.1705,1716.8708,61.312763,GSW,Warriors,93,1806.2035,1797.5032,A,W,0.242326,NaN
126305,63153,201506070GSW,NBA,0,2015,6/7/2015,99,1,GSW,Warriors,93,1806.2035,1797.5032,67.029549,CLE,Cavaliers,95,1708.1705,1716.8708,H,L,0.757674,NaN
126306,63154,201506090CLE,NBA,1,2015,6/9/2015,100,1,GSW,Warriors,91,1797.5032,1790.9591,66.615417,CLE,Cavaliers,96,1716.8708,1723.4149,A,L,0.472157,NaN
126307,63154,201506090CLE,NBA,0,2015,6/9/2015,99,1,CLE,Cavaliers,96,1716.8708,1723.4149,61.826408,GSW,Warriors,91,1797.5032,1790.9591,H,W,0.527843,NaN
126308,63155,201506110CLE,NBA,1,2015,6/11/2015,101,1,GSW,Warriors,103,1790.9591,1809.9791,67.794983,CLE,Cavaliers,82,1723.4149,1704.3949,A,W,0.453428,NaN
126309,63155,201506110CLE,NBA,0,2015,6/11/2015,100,1,CLE,Cavaliers,82,1723.4149,1704.3949,60.309792,GSW,Warriors,103,1790.9591,1809.9791,H,L,0.546572,NaN
126310,63156,201506140GSW,NBA,0,2015,6/14/2015,102,1,GSW,Warriors,104,1809.9791,1813.6349,68.013329,CLE,Cavaliers,91,1704.3949,1700.7391,H,W,0.765565,NaN
126311,63156,201506140GSW,NBA,1,2015,6/14/2015,101,1,CLE,Cavaliers,91,1704.3949,1700.7391,60.010067,GSW,Warriors,104,1809.9791,1813.6349,A,L,0.234435,NaN
126312,63157,201506170CLE,NBA,0,2015,6/16/2015,102,1,CLE,Cavaliers,97,1700.7391,1692.0859,59.290245,GSW,Warriors,105,1813.6349,1822.2881,H,L,0.481450,NaN
126313,63157,201506170CLE,NBA,1,2015,6/16/2015,103,1,GSW,Warriors,105,1813.6349,1822.2881,68.519516,CLE,Cavaliers,97,1700.7391,1692.0859,A,W,0.518550,NaN

# select the rows where a specific field is not null. 
We have NaN in the column of 'notes'<br>
This can be helpful,to avoid any missing values in a column.

In [9]:
games_with_notes = nba[nba['notes'].notnull()]

In [11]:
games_with_notes.head(10)

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
930,466,194801300BLB,NBA,1,1948,1/30/1948,28,0,WSC,Capitols,71,1469.3469,1454.9012,47.065742,BLB,Baltimore,95,1434.0548,1448.5005,A,L,0.407940,at Baltimore's Fifth Regiment Armory
931,466,194801300BLB,NBA,0,1948,1/30/1948,31,0,BLB,Baltimore,95,1434.0548,1448.5005,46.407490,WSC,Capitols,71,1469.3469,1454.9012,H,W,0.592060,at Baltimore's Fifth Regiment Armory
1084,543,194803230CHS,NBA,1,1948,3/23/1948,49,1,WSC,Capitols,70,1465.9006,1461.1990,47.710297,CHS,Stags,74,1440.7186,1445.4203,A,L,0.393962,Tiebreaker
1085,543,194803230CHS,NBA,0,1948,3/23/1948,49,1,CHS,Stags,74,1440.7186,1445.4203,46.089687,WSC,Capitols,70,1465.9006,1461.1990,H,W,0.606038,Tiebreaker
1088,545,194803250CHS,NBA,1,1948,3/25/1948,49,1,BLB,Baltimore,75,1477.2552,1484.3137,50.044666,CHS,Stags,72,1445.4203,1438.3618,A,W,0.403142,Tiebreaker
1089,545,194803250CHS,NBA,0,1948,3/25/1948,50,1,CHS,Stags,72,1445.4203,1438.3618,45.359138,BLB,Baltimore,75,1477.2552,1484.3137,H,L,0.596858,Tiebreaker
1212,607,194811190BLB,NBA,1,1949,11/19/1948,6,0,STB,Bombers,82,1444.9471,1460.0862,42.818317,BLB,Baltimore,72,1461.3345,1446.1954,A,W,0.338501,at Chicago IL
1213,607,194811190BLB,NBA,0,1949,11/19/1948,8,0,BLB,Baltimore,72,1461.3345,1446.1954,41.362427,STB,Bombers,82,1444.9471,1460.0862,H,L,0.661499,at Chicago IL
1264,633,194811300BOS,NBA,1,1949,11/30/1948,14,0,MNL,Lakers,94,1557.3899,1564.6674,53.390305,BOS,Celtics,84,1368.9742,1361.6968,A,W,0.624563,at Chicago IL
1265,633,194811300BOS,NBA,0,1949,11/30/1948,13,0,BOS,Celtics,84,1368.9742,1361.6968,32.618668,MNL,Lakers,94,1557.3899,1564.6674,H,L,0.375437,at Chicago IL

.notna() also be used to achieve the same goal.(removing NaN rows)

In [13]:
games_without_null = nba[nba['notes'].notna()]

In [15]:
games_without_null.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
930,466,194801300BLB,NBA,1,1948,1/30/1948,28,0,WSC,Capitols,71,1469.3469,1454.9012,47.065742,BLB,Baltimore,95,1434.0548,1448.5005,A,L,0.407940,at Baltimore's Fifth Regiment Armory
931,466,194801300BLB,NBA,0,1948,1/30/1948,31,0,BLB,Baltimore,95,1434.0548,1448.5005,46.407490,WSC,Capitols,71,1469.3469,1454.9012,H,W,0.592060,at Baltimore's Fifth Regiment Armory
1084,543,194803230CHS,NBA,1,1948,3/23/1948,49,1,WSC,Capitols,70,1465.9006,1461.1990,47.710297,CHS,Stags,74,1440.7186,1445.4203,A,L,0.393962,Tiebreaker
1085,543,194803230CHS,NBA,0,1948,3/23/1948,49,1,CHS,Stags,74,1440.7186,1445.4203,46.089687,WSC,Capitols,70,1465.9006,1461.1990,H,W,0.606038,Tiebreaker
1088,545,194803250CHS,NBA,1,1948,3/25/1948,49,1,BLB,Baltimore,75,1477.2552,1484.3137,50.044666,CHS,Stags,72,1445.4203,1438.3618,A,W,0.403142,Tiebreaker

# access values of the object data type as str and perform string methods

In [16]:
# use .str.endswith() to filter your dataset and find all games where the home team’s name ends with "ers".
ers = nba[nba['fran_id'].str.endswith('ers')]

In [18]:
ers.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
7,4,194611020PRO,NBA,0,1947,11/2/1946,1,0,PRO,Steamrollers,59,1300.0000,1305.1542,41.540619,BOS,Celtics,53,1300.0000,1294.8458,H,W,0.640065,NaN
9,5,194611020STB,NBA,0,1947,11/2/1946,1,0,STB,Bombers,56,1300.0000,1304.6908,41.492020,PIT,Ironmen,51,1300.0000,1295.3092,H,W,0.640065,NaN
16,9,194611050DTF,NBA,1,1947,11/5/1946,2,0,STB,Bombers,53,1304.6908,1312.8473,42.347137,DTF,Falcons,49,1279.6189,1271.4624,A,W,0.393811,NaN
20,11,194611070PRO,NBA,0,1947,11/7/1946,2,0,PRO,Steamrollers,73,1305.1542,1311.5032,42.206284,CHS,Stags,65,1316.0840,1309.7350,H,W,0.625446,NaN
22,12,194611070STB,NBA,0,1947,11/7/1946,3,0,STB,Bombers,63,1312.8473,1302.5988,41.272594,NYK,Knicks,68,1297.0712,1307.3197,H,L,0.660710,NaN

# teamId ends with K

In [19]:
ends_with_k = nba[nba['team_id'].str.endswith('K')]

In [22]:
ends_with_k

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,68,1300.0000,1306.7233,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,47,1306.7233,1297.0712,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
23,12,194611070STB,NBA,1,1947,11/7/1946,3,0,NYK,Knicks,68,1297.0712,1307.3197,41.767715,STB,Bombers,63,1312.8473,1302.5988,A,W,0.339290,NaN
37,19,194611110NYK,NBA,0,1947,11/11/1946,4,0,NYK,Knicks,68,1307.3197,1293.2161,40.288467,CHS,Stags,78,1315.2522,1329.3558,H,L,0.629479,NaN
54,28,194611160NYK,NBA,0,1947,11/16/1946,5,0,NYK,Knicks,64,1293.2161,1296.2185,40.603352,PIT,Ironmen,62,1277.5587,1274.5563,H,W,0.660557,NaN
62,32,194611180NYK,NBA,0,1947,11/18/1946,6,0,NYK,Knicks,61,1296.2185,1300.3541,41.037148,DTF,Falcons,57,1291.9098,1287.7742,H,W,0.645759,NaN
72,37,194611200NYK,NBA,0,1947,11/20/1946,7,0,NYK,Knicks,72,1300.3541,1304.5542,41.477695,CHS,Stags,69,1328.0181,1323.8180,H,W,0.602621,NaN
87,44,194611230NYK,NBA,0,1947,11/23/1946,8,0,NYK,Knicks,82,1304.5542,1309.9252,42.040882,CLR,Rebels,76,1313.9331,1308.5621,H,W,0.627535,NaN
98,50,194611250PIT,NBA,1,1947,11/25/1946,9,0,NYK,Knicks,62,1309.9252,1327.9469,43.926521,PIT,Ironmen,46,1282.9152,1264.8934,A,W,0.396477,NaN
107,54,194611270NYK,NBA,0,1947,11/27/1946,10,0,NYK,Knicks,67,1327.9469,1333.9167,44.548813,STB,Bombers,60,1342.2628,1336.2930,H,W,0.620869,NaN
119,60,194611280PRO,NBA,1,1947,11/28/1946,11,0,NYK,Knicks,60,1333.9167,1339.6215,45.141937,PRO,Steamrollers,58,1281.3928,1275.6881,A,W,0.432099,NaN
122,62,194611300NYK,NBA,0,1947,11/30/1946,12,0,NYK,Knicks,64,1339.6215,1342.8893,45.480927,PHW,Warriors,60,1284.4366,1281.1688,H,W,0.709574,NaN
139,70,194612040NYK,NBA,0,1947,12/4/1946,13,0,NYK,Knicks,70,1342.8893,1350.4919,46.267113,DTF,Falcons,57,1326.9114,1319.3087,H,W,0.660971,NaN
148,75,194612050GSW,NBA,1,1947,12/5/1946,14,0,NYK,Knicks,51,1350.4919,1340.9235,45.277073,PHW,Warriors,62,1287.2725,1296.8409,A,L,0.447265,NaN
153,77,194612070BOS,NBA,1,1947,12/7/1946,15,0,NYK,Knicks,90,1340.9235,1359.2839,47.171368,BOS,Celtics,65,1229.3071,1210.9467,A,W,0.516711,NaN
165,83,194612080NYK,NBA,0,1947,12/8/1946,16,0,NYK,Knicks,62,1359.2839,1364.1929,47.673653,BOS,Celtics,44,1210.9467,1206.0377,H,W,0.806830,NaN
175,88,194612110NYK,NBA,0,1947,12/11/1946,17,0,NYK,Knicks,83,1364.1929,1369.5447,48.218910,PRO,Steamrollers,68,1256.0878,1250.7360,H,W,0.768160,NaN
194,98,194612150CLR,NBA,1,1947,12/15/1946,18,0,NYK,Knicks,52,1369.5447,1355.8319,46.817009,CLR,Rebels,70,1297.2839,1310.9967,A,L,0.460165,NaN
205,103,194612180NYK,NBA,0,1947,12/18/1946,19,0,NYK,Knicks,53,1355.8319,1347.1748,45.924538,CLR,Rebels,56,1317.8322,1326.4893,H,L,0.688773,NaN
214,108,194612200TRH,NBA,1,1947,12/20/1946,20,0,NYK,Knicks,70,1347.1748,1340.5975,45.243252,TRH,Huskies,74,1236.3962,1242.9735,A,L,0.515507,NaN
217,109,194612210PRO,NBA,1,1947,12/21/1946,21,0,NYK,Knicks,61,1340.5975,1336.2484,44.791435,PRO,Steamrollers,63,1268.4114,1272.7605,A,L,0.460058,NaN
241,121,194612280WSC,NBA,1,1947,12/28/1946,22,0,NYK,Knicks,49,1336.2484,1329.1947,44.056713,WSC,Capitols,70,1435.3077,1442.3615,A,L,0.241243,NaN
269,135,194701040DTF,NBA,1,1947,1/4/1947,23,0,NYK,Knicks,62,1329.1947,1343.4509,45.539127,DTF,Falcons,50,1287.9642,1273.7080,A,W,0.416221,NaN
275,138,194701050STB,NBA,1,1947,1/5/1947,24,0,NYK,Knicks,59,1343.4509,1350.6637,46.284832,STB,Bombers,57,1368.0355,1360.8228,A,W,0.328017,NaN
285,143,194701080NYK,NBA,0,1947,1/8/1947,25,0,NYK,Knicks,63,1350.6637,1328.6687,44.001839,TRH,Huskies,76,1253.9355,1275.9305,H,L,0.756292,NaN
296,149,194701100BOS,NBA,1,1947,1/10/1947,26,0,NYK,Knicks,62,1328.6687,1321.4895,43.251884,BOS,Celtics,66,1192.8752,1200.0544,A,L,0.551329,NaN
308,155,194701130PIT,NBA,1,1947,1/13/1947,27,0,NYK,Knicks,53,1321.4895,1326.8982,43.817055,PIT,Ironmen,50,1212.5773,1207.1686,A,W,0.512823,NaN
316,159,194701150NYK,NBA,0,1947,1/15/1947,28,0,NYK,Knicks,63,1326.8982,1322.4481,43.352123,WSC,Capitols,65,1448.7782,1453.2283,H,L,0.468554,NaN
328,165,194701180NYK,NBA,0,1947,1/18/1947,29,0,NYK,Knicks,45,1322.4481,1300.2828,41.029667,BOS,Celtics,58,1222.4307,1244.5959,H,L,0.759765,NaN
332,167,194701190CLR,NBA,1,1947,1/19/1947,30,0,NYK,Knicks,72,1300.2828,1294.4644,40.419373,CLR,Rebels,79,1291.8809,1297.6993,A,L,0.371151,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125810,62906,201503250CHO,NBA,1,2015,3/25/2015,70,0,BRK,Nets,91,1441.8984,1450.0525,35.321339,CHO,Hornets,88,1458.2108,1450.0568,A,W,0.338598,NaN
125820,62911,201503250NYK,NBA,0,2015,3/25/2015,72,0,NYK,Knicks,80,1266.2123,1260.5667,18.284536,LAC,Clippers,111,1659.9270,1665.5728,H,L,0.155676,NaN
125838,62920,201503270BRK,NBA,0,2015,3/27/2015,71,0,BRK,Nets,106,1450.0525,1463.7366,36.735481,CLE,Cavaliers,98,1678.1150,1664.4309,H,W,0.323620,NaN
125849,62925,201503270NYK,NBA,0,2015,3/27/2015,73,0,NYK,Knicks,92,1260.5667,1256.3702,17.981283,BOS,Celtics,96,1461.5897,1465.7861,H,L,0.358579,NaN
125863,62932,201503280CHI,NBA,1,2015,3/28/2015,74,0,NYK,Knicks,80,1256.3702,1253.1930,17.754097,CHI,Bulls,111,1551.2925,1554.4697,A,L,0.093354,NaN
125874,62938,201503290BRK,NBA,0,2015,3/29/2015,72,0,BRK,Nets,107,1463.7366,1467.0745,37.082123,LAL,Lakers,99,1340.4608,1337.1229,H,W,0.783347,NaN
125904,62953,201503310BRK,NBA,0,2015,3/31/2015,73,0,BRK,Nets,111,1467.0745,1471.7891,37.572689,IND,Pacers,106,1468.2207,1463.5061,H,W,0.638543,NaN
125924,62963,201504010NYK,NBA,0,2015,4/1/2015,75,0,NYK,Knicks,98,1253.1930,1250.2303,17.544134,BRK,Nets,100,1471.7891,1474.7517,H,L,0.335660,NaN
125925,62963,201504010NYK,NBA,1,2015,4/1/2015,74,0,BRK,Nets,100,1471.7891,1474.7517,37.881474,NYK,Knicks,98,1253.1930,1250.2303,A,W,0.664340,NaN
125944,62973,201504030BRK,NBA,0,2015,4/3/2015,75,0,BRK,Nets,114,1474.7517,1480.8125,38.514240,TOR,Raptors,109,1535.7175,1529.6567,H,W,0.555940,NaN
125960,62981,201504030WAS,NBA,1,2015,4/3/2015,76,0,NYK,Knicks,87,1250.2303,1247.7606,17.370491,WAS,Wizards,101,1492.5874,1495.0571,A,L,0.122307,NaN
125962,62982,201504040ATL,NBA,1,2015,4/4/2015,76,0,BRK,Nets,99,1480.8125,1472.3794,37.634186,ATL,Hawks,131,1603.9235,1612.3566,A,L,0.216814,NaN
125989,62995,201504050NYK,NBA,0,2015,4/5/2015,77,0,NYK,Knicks,101,1247.7606,1256.8353,18.014713,PHI,Sixers,91,1312.5758,1303.5011,H,W,0.550463,NaN
125996,62999,201504060BRK,NBA,0,2015,4/6/2015,77,0,BRK,Nets,106,1472.3794,1484.8717,38.938721,POR,Trailblazers,96,1625.7427,1613.2504,H,W,0.423802,NaN
126010,63006,201504080BRK,NBA,0,2015,4/8/2015,78,0,BRK,Nets,111,1484.8717,1479.9816,38.427414,ATL,Hawks,114,1619.9884,1624.8785,H,L,0.449634,NaN
126025,63013,201504080NYK,NBA,0,2015,4/8/2015,78,0,NYK,Knicks,86,1256.8353,1248.3544,17.412123,IND,Pacers,102,1478.9901,1487.4711,H,L,0.331108,NaN
126043,63022,201504100BRK,NBA,0,2015,4/10/2015,79,0,BRK,Nets,117,1479.9816,1500.6542,40.592506,WAS,Wizards,80,1525.9258,1505.2532,H,W,0.577171,NaN
126056,63029,201504100NYK,NBA,0,2015,4/10/2015,79,0,NYK,Knicks,91,1248.3544,1242.4070,16.998409,MIL,Bucks,99,1452.2738,1458.2212,H,L,0.354754,NaN
126072,63037,201504110ORL,NBA,1,2015,4/11/2015,80,0,NYK,Knicks,80,1242.4070,1249.4366,17.488194,ORL,Magic,79,1325.8820,1318.8523,A,W,0.258043,NaN
126089,63045,201504120MIL,NBA,1,2015,4/12/2015,80,0,BRK,Nets,73,1500.6542,1486.2174,39.079548,MIL,Bucks,96,1458.2212,1472.6580,A,L,0.417904,NaN
126094,63048,201504130ATL,NBA,1,2015,4/13/2015,81,0,NYK,Knicks,112,1249.4366,1268.4222,18.861967,ATL,Hawks,108,1618.9574,1599.9718,A,W,0.062810,NaN
126096,63049,201504130BRK,NBA,0,2015,4/13/2015,81,0,BRK,Nets,86,1486.2174,1463.5762,36.718838,CHI,Bulls,113,1554.9941,1577.6354,H,L,0.544813,NaN
126124,63063,201504150BRK,NBA,0,2015,4/15/2015,82,0,BRK,Nets,101,1463.5762,1467.5382,37.130329,ORL,Magic,88,1315.8535,1311.8915,H,W,0.806278,NaN
126147,63074,201504150NYK,NBA,0,2015,4/15/2015,82,0,NYK,Knicks,90,1268.4222,1255.6846,17.932079,DET,Pistons,112,1448.3408,1461.0784,H,L,0.386974,NaN
126161,63081,201504190ATL,NBA,1,2015,4/19/2015,83,1,BRK,Nets,92,1467.5382,1464.5007,36.814785,ATL,Hawks,99,1594.2922,1597.3297,A,L,0.213274,NaN
126179,63090,201504220ATL,NBA,1,2015,4/22/2015,84,1,BRK,Nets,91,1464.5007,1462.0392,36.559437,ATL,Hawks,96,1597.3297,1599.7913,A,L,0.207465,NaN
126197,63099,201504250BRK,NBA,0,2015,4/25/2015,85,1,BRK,Nets,91,1462.0392,1472.4146,37.637848,ATL,Hawks,83,1599.7913,1589.4159,H,W,0.445883,NaN
126213,63107,201504270BRK,NBA,0,2015,4/27/2015,86,1,BRK,Nets,120,1472.4146,1479.8978,38.418663,ATL,Hawks,115,1589.4159,1581.9326,H,W,0.475553,NaN
126223,63112,201504290ATL,NBA,1,2015,4/29/2015,87,1,BRK,Nets,97,1479.8978,1475.6433,37.974476,ATL,Hawks,107,1581.9326,1586.1871,A,L,0.238122,NaN
126231,63116,201505010BRK,NBA,0,2015,5/1/2015,88,1,BRK,Nets,87,1475.6433,1457.7372,36.114021,ATL,Hawks,111,1586.1871,1604.0933,H,L,0.484831,NaN

# game_Id ends with 'LB'

In [23]:
game_id_endswith_LB = nba[nba['game_id'].str.endswith('LB')]

In [25]:
game_id_endswith_LB.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
702,352,194711130BLB,NBA,0,1948,11/13/1947,2,0,BLB,Baltimore,85,1414.4618,1418.4851,43.288319,BOS,Celtics,74,1289.9966,1285.9733,H,W,0.784507,NaN
703,352,194711130BLB,NBA,1,1948,11/13/1947,1,0,BOS,Celtics,74,1289.9966,1285.9733,29.691414,BLB,Baltimore,85,1414.4618,1418.4851,A,L,0.215493,NaN
728,365,194711200BLB,NBA,1,1948,11/20/1947,5,0,NYK,Knicks,56,1378.5894,1372.4034,38.460194,BLB,Baltimore,68,1427.8206,1434.0065,A,L,0.297539,NaN
729,365,194711200BLB,NBA,0,1948,11/20/1947,4,0,BLB,Baltimore,68,1427.8206,1434.0065,44.906929,NYK,Knicks,56,1378.5894,1372.4034,H,W,0.702461,NaN
738,370,194711220BLB,NBA,1,1948,11/22/1947,5,0,CHS,Stags,72,1453.5292,1449.6821,46.529236,BLB,Baltimore,75,1446.2875,1450.1345,A,L,0.369594,NaN

# combine multiple criteria and query of your dataset as well. To do this, be sure to put each one in parentheses and use the logical operators | and & to separate them.

In [30]:
combination = nba[

    (nba['team_id'] == 'BLB') &
    (nba['_iscopy'] == 0) &
    (nba['pts'] > 100 )&
    (nba['opp_pts'] > 100)
]

In [31]:
combination.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
1726,864,194902260BLB,NBA,0,1949,2/26/1949,53,0,BLB,Baltimore,114,1421.9351,1419.4280,38.557545,MNL,Lakers,115,1637.9852,1640.4923,H,L,0.338936,NaN
4890,2446,195301100BLB,NBA,0,1953,1/10/1953,32,0,BLB,Baltimore,126,1328.6687,1356.6470,25.797792,BOS,Celtics,105,1591.1434,1563.1652,H,W,0.281855,NaN
4909,2455,195301140BLB,NBA,0,1953,1/14/1953,34,0,BLB,Baltimore,104,1349.8323,1346.3594,24.876236,MNL,Lakers,112,1665.4396,1668.9125,H,L,0.224238,NaN
5208,2605,195303110BLB,NBA,0,1953,3/11/1953,66,0,BLB,Baltimore,107,1284.5239,1282.2396,19.579676,NYK,Knicks,113,1649.1516,1651.4359,H,L,0.178973,at Boston MA
5825,2913,195402220BLB,NBA,0,1954,2/22/1954,60,0,BLB,Baltimore,110,1303.7493,1301.9685,20.736986,BOS,Celtics,111,1591.4943,1593.2749,H,L,0.253365,at Worcester MA

In the spring of 1992, both teams from Los Angeles had to play a home game at another court. Query your dataset to find those two games. Both teams have an ID starting with "LA".

In [33]:
nba[
    (nba['_iscopy']== 0)&
    (nba['year_id'] == 1992) &
    (nba['game_id'].str.startswith('LA'))&
    (nba['notes'].notnull())
]

Empty DataFrame
Columns: [gameorder, game_id, lg_id, _iscopy, year_id, date_game, seasongame, is_playoffs, team_id, fran_id, pts, elo_i, elo_n, win_equiv, opp_id, opp_fran, opp_pts, opp_elo_i, opp_elo_n, game_location, game_result, forecast, notes]
Index: []

In [34]:
nba[
    (nba["_iscopy"] == 0) &
    (nba["team_id"].str.startswith("LA")) &
    (nba["year_id"]==1992) &
    (nba["notes"].notnull())
]

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,pts,elo_i,elo_n,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
68901,34451,199205030LAC,NBA,0,1992,5/3/1992,86,1,LAC,Clippers,115,1546.9009,1556.0005,47.888252,UTA,Jazz,107,1647.5092,1638.4095,H,W,0.499125,"at Anaheim, CA (Anaheim Convention Center)"
68903,34452,199205030LAL,NBA,0,1992,5/3/1992,86,1,LAL,Lakers,76,1489.6460,1474.3994,39.395412,POR,Trailblazers,102,1655.1210,1670.3677,H,L,0.406874,"at Las Vegas, NV"